[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enableNextJsLink = true
    enableNextJsSass = true

[dev]
  framework = "next"
  command = "npm run dev"
  targetPort = 3000
  publish = ".next"
  port = 3000
