[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  # Node.js and build settings
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Next.js optimizations
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_IGNORE_ESLINT = "1"
  NEXT_IGNORE_TYPECHECK = "1"
  
  # Environment validation
  SKIP_ENV_VALIDATION = "true"
  NETLIFY_NEXT_PLUGIN_FORCE_RUN = "true"
  
  # Application environment variables (set these in Netlify UI)
  BETTER_AUTH_SECRET = ""
  BETTER_AUTH_URL = ""
  DATABASE_URL = ""
  GITHUB_CLIENT_ID = ""
  GITHUB_CLIENT_SECRET = ""
  GOOGLE_CLIENT_ID = ""
  GOOGLE_CLIENT_SECRET = ""
  DISCORD_CLIENT_ID = ""
  DISCORD_CLIENT_SECRET = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enableServerComponents = true
    staticOptimization = true

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = ".next"
  port = 3000
  framework = "next"

[functions]
  directory = ".next/server/functions"
  node_bundler = "esbuild"
