[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # No additional inputs needed for the plugin

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = ".next"
  port = 3000
