[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_IGNORE_ESLINT = "1"
  NEXT_IGNORE_TYPECHECK = "1"
  SKIP_ENV_VALIDATION = "true"
  NETLIFY_NEXT_PLUGIN_FORCE_RUN = "true"
  DATABASE_URL = "postgresql://titan_owner:npg_XiZegLY9bWz7@ep-curly-thunder-a8r4hkmh-pooler.eastus2.azure.neon.tech/titan?sslmode=require"
  BETTER_AUTH_URL = "/api/auth"
  BETTER_AUTH_SECRET = "Vizo94MsrmVjWUyHB03bhooIkriDrOu6"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = ".next"
  port = 3000
  framework = "next"

[functions]
  directory = ".next/server/functions"
  node_bundler = "esbuild"
